- name: Cargo is installed check
  ansible.builtin.stat:
    path: "{{ lookup('env', 'HOME') }}/.cargo"
  register: cargo_installation
- name: Download rustup install script
  when: cargo_installation.stat.exists == false
  ansible.builtin.get_url:
    dest: "{{ lookup('env', 'HOME') }}/Downloads/rustup_install.sh"
    url: https://sh.rustup.rs
    mode: "0777"
- name: Invoke rustup install script
  when: cargo_installation.stat.exists == false
  ansible.builtin.command:
    argv:
      - "{{ lookup('env', 'HOME') }}/Downloads/rustup_install.sh"
      - "-y"
