- name: rtx is installed check
  ansible.builtin.stat:
    path: "{{ lookup('env', 'HOME') }}/.local/bin/rtx"
  register: rtx_installation
- name: Download rtx install script
  when: rtx_installation.stat.exists == false
  ansible.builtin.get_url:
    dest: "{{ lookup('env', 'HOME') }}/Downloads/rtx_install.sh"
    url: https://rtx.pub/install.sh
    mode: "0777"
- name: Invoke rtx install script
  when: rtx_installation.stat.exists == false
  ansible.builtin.command:
    argv:
      - "{{ lookup('env', 'HOME') }}/Downloads/rtx_install.sh"
  environment:
    RTX_INSTALL_PATH: "{{ lookup('env', 'HOME') }}/.local/bin/rtx"
