- name: Install flatpak
  ansible.builtin.package:
    name:
      - flatpak
    state: present
  become: true
- name: Check for flathub repository
  shell: flatpak remotes --columns url | grep flathub
  register: flathub_check
- name: Add flathub repository
  when: flathub_check.rc != 0
  ansible.builtin.command: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
- name: Install packages from flatpak
  community.general.flatpak:
    name:
      - com.visualstudio.code
      - org.gimp.GIMP
      - org.videolan.VLC
      - io.podman_desktop.PodmanDesktop
      - org.mozilla.firefox
      - org.kde.okular
      - us.zoom.Zoom
      - org.signal.Signal
      - com.discordapp.Discord
      - com.spotify.Client
      - com.valvesoftware.Steam
    state: present
