- name: Install zsh from package manager
  ansible.builtin.package:
    name:
      - zsh
      - git
  become: true
- name: OhMyZsh is installed check
  ansible.builtin.stat:
    path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
  register: omz_installation
- name: Download ohmyzsh install script
  when: omz_installation.stat.exists == false
  ansible.builtin.get_url:
    dest: "{{ lookup('env', 'HOME') }}/Downloads/omzinstall.sh"
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    mode: "0777"
- name: Invoke ohmyzsh install script
  when: omz_installation.stat.exists == false
  ansible.builtin.command:
    argv:
      - "{{ lookup('env', 'HOME') }}/Downloads/omzinstall.sh"
      - "--unattended"
      - "--skip-chsh"
      - "--keep-zshrc"
- name: Add zsh-syntax-highlighting plugin
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/plugins/zsh-syntax-highlighting"
- name: Make user shell zsh
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: true